[project]
name = "motor-control-via-hand-gesture-with-rtos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keyboard>=0.13.5",
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
]
